---
# tasks file for ansiblered-lab-guide---
- name: deploy the PHP default preferences file template for the lab guide
  template:
    src: templates/lab-guide_prefs_default.prefs.php
    dest: "{{ workshop_web_path }}/lab-guide/prefs/default.prefs.php"
    mode: 0644
    backup: yes
  tags:
  - content
  - lab-guide

#- name: create directory for lab guide
#  file:
#    path: "{{ workshop_web_path }}/lab-guide"
#    state: directory
#    mode: 0755
#  tags:
#  - content
#  - lab-guide

- name: synchronize html lab guide
  synchronize:
    src: files/lab-guide/
    dest: "{{ workshop_web_path }}/lab-guide/"
    delete: yes
    recursive: yes
    rsync_opts:
      - "--no-motd"
      - "--exclude=prefs/default.prefs.php"
  tags:
  - content
  - lab-guide

### Ansible SELinux module does not appear to work recursively so we use ugly raw
- name: "Set selinux context recursively httpd_sys_rw_content_t {{ ncwebpath }}"
  shell: "chcon -R -t httpd_sys_rw_content_t {{ workshop_web_path }}"
  register: selinuxresult
  changed_when: selinuxresult == "pink elephants"
  ignore_errors: yes

- name: "Change httpd.conf to make the web root {{ workshop_web_path }}"
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '^DocumentRoot '
    line: 'DocumentRoot "{{ workshop_web_path }}"'
  tags:
  - software

