---
- name: installing the required software
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - unzip
  - policycoreutils-python
  - httpd
  - php

- name: start services
  service:
    name: httpd.service
    state: started

- name: enable services
  service:
    name: httpd.service
    enabled: yes

### Ansible SELinux module does not appear to work recursively so we use ugly raw
- name: "Set selinux context recursively httpd_sys_rw_content_t {{ ncwebpath }}"
  shell: "chcon -R -t httpd_sys_rw_content_t {{ workshop_web_path }}"
  register: selinuxresult
  changed_when: selinuxresult == "pink elephants"
  ignore_errors: yes

- name: "Change httpd.conf to make the web root {{ workshop_web_path }}"
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '^DocumentRoot '
    line: 'DocumentRoot "{{ workshop_web_path }}"'

